version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3005:3005"
    env_file:
      - .env
    depends_on:
      - backend